params:
  NumCond:
    group: "Experimental Design"
    type: "paramGroundTruth"
    description: "Number of conditions."
    min: 2
    max: 10
    default: 2
  NumReps:
    group: "Experimental Design"
    type: "paramGroundTruth"
    description: "Number of replicates."
    min: 1
    max: 10
    default: 3
  PathToFasta:
    group: "Input Data"
    type: "paramGroundTruth"
    description: "Path to input FASTA file."
    min: NA
    max: NA
    default: "fasta_full_yeast.fasta"
  PathToProteinList:
    group: "Input Data"
    type: "paramGroundTruth"
    description: "Path to input protein list (optional)."
    min: NA
    max: NA
    default: NA
  FracModProt:
    group: "Ground Truth Data"
    type: "paramGroundTruth"
    description: "Fraction of proteins selected to be modified (0 for none, 1 for all)."
    min: 0
    max: 1
    default: 0
  FracModPerProt:
    group: "Ground Truth Data"
    type: "paramGroundTruth"
    description: "Factor for generating more proteoforms from selected proteins."
    min: 0
    max: 5
    default: 0
  PTMTypes:
    group: "Ground Truth Data"
    type: "paramGroundTruth"
    description: "Types of post-translational modifications (PTMs)."
    min: NA
    max: NA
    default: NA
  PTMTypesDist:
    group: "Ground Truth Data"
    type: "paramGroundTruth"
    description: "Distribution of PTM types."
    min: 0
    max: 1
    default: NA
  PTMTypesMass:
    group: "Ground Truth Data"
    type: "paramGroundTruth"
    description: "Mass shifts for each PTM type."
    min: 0
    max: 200
    default: NA
  PTMMultipleLambda:
    group: "Ground Truth Data"
    type: "paramGroundTruth"
    description: "Poisson parameter for multiply modified proteins, scaled to the number of possible PTM sites."
    min: 0
    max: 5
    default: NA
  ModifiableResidues:
    group: "Ground Truth Data"
    type: "paramGroundTruth"
    description: "Residues that can be modified for each PTM type."
    min: NA
    max: NA
    default: NA
  ModifiableResiduesDistr:
    group: "Ground Truth Data"
    type: "paramGroundTruth"
    description: "Distribution of modifications across residues."
    min: 0
    max: 1
    default: NA
  RemoveNonModFormFrac:
    group: "Ground Truth Data"
    type: "paramGroundTruth"
    description: "Percentage of modifiable proteins without non-modified forms."
    min: 0
    max: 1
    default: 0
  QuantNoise:
    group: "Proteoform Quantities"
    type: "paramProteoformAb"
    description: "Noise level of quantitative values (standard deviation)."
    min: 0
    max: 5
    default: 0.5
  DiffRegFrac:
    group: "Proteoform Quantities"
    type: "paramProteoformAb"
    description: "Fraction of differentially regulated proteoforms."
    min: 0
    max: 1
    default: 0.3
  DiffRegMax:
    group: "Proteoform Quantities"
    type: "paramProteoformAb"
    description: "Maximum amplitude of difference for differentially regulated proteoforms (log2 scale)."
    min: 0
    max: 10
    default: 1
  UserInputFoldChanges_NumRegProteoforms:
    group: "Proteoform Quantities"
    type: "paramProteoformAb"
    description: "Custom set of regulated proteoforms (optional). Number of regulated proteoforms"
    min: NA
    max: NA
    default: NA
  UserInputFoldChanges_RegulationFC:
    group: "Proteoform Quantities"
    type: "paramProteoformAb"
    description: "Custom set of regulated proteoforms (optional). Fold change of regulation."
    min: NA
    max: NA
    default: NA
  ThreshNAProteoform:
    group: "Proteoform Quantities"
    type: "paramProteoformAb"
    description: "Threshold to remove quantitative values at the proteoform level."
    min: 0
    max: 1000
    default: 0
  AbsoluteQuanMean:
    group: "Proteoform Quantities"
    type: "paramProteoformAb"
    description: "Mean for absolute quantification."
    min: 0
    max: 100
    default: 30.5
  AbsoluteQuanSD:
    group: "Proteoform Quantities"
    type: "paramProteoformAb"
    description: "Standard deviation for absolute quantification."
    min: 0
    max: 10
    default: 3.6
  ThreshNAQuantileProt:
    group: "Proteoform Quantities"
    type: "paramProteoformAb"
    description: "Quantile threshold for removing quantitative values."
    min: 0
    max: 1
    default: 0.01
  Enzyme:
    group: "Enzymatic Digestion"
    type: "paramDigest"
    description: "Enzyme used for digestion (e.g., trypsin)."
    min: NA
    max: NA
    default: "trypsin"
  PropMissedCleavages:
    group: "Enzymatic Digestion"
    type: "paramDigest"
    description: "Proportion of peptides with missed cleavages."
    min: 0
    max: 1
    default: 0.01
  MaxNumMissedCleavages:
    group: "Enzymatic Digestion"
    type: "paramDigest"
    description: "Maximum number of missed cleavages per peptide."
    min: 0
    max: 10
    default: 2
  PepMinLength:
    group: "Enzymatic Digestion"
    type: "paramDigest"
    description: "Minimum peptide length."
    min: 1
    max: 50
    default: 7
  PepMaxLength:
    group: "Enzymatic Digestion"
    type: "paramDigest"
    description: "Maximum peptide length."
    min: 1
    max: 50
    default: 30
  LeastAbundantLoss:
    group: "Enzymatic Digestion"
    type: "paramDigest"
    description: "Percentage of least abundant peptides to remove."
    min: 0
    max: 1
    default: 0
  EnrichmentLoss:
    group: "Sample Preparation"
    type: "paramDigest"
    description: "Percentage loss of peptides during enrichment."
    min: 0
    max: 1
    default: 0.2
  EnrichmentEfficiency:
    group: "Sample Preparation"
    type: "paramDigest"
    description: "Efficiency of enrichment for modified peptides."
    min: 0
    max: 1
    default: 1
  EnrichmentNoise:
    group: "Sample Preparation"
    type: "paramDigest"
    description: "Noise due to enrichment protocol."
    min: 0
    max: 1
    default: 0.2
  DetectabilityThreshold:
    group: "MS Run"
    type: "paramMSRun"
    description: "Threshold for detectibility of peptides from PeptideRanger predictions (trained on ProteomicsDB)."
    min: 0
    max: 1
    default: 0.5
  # PercDetectedPep:
  #   group: "MS Run"
  #   type: "paramMSRun"
  #   description: "Percentage of detected peptides."
  #   min: 0
  #   max: 1
  #   default: 0.2
  PercDetectedVal:
    group: "MS Run"
    type: "paramMSRun"
    description: "Percentage of detected values (replicate/condition)."
    min: 0
    max: 1
    default: 0.5
  WeightDetectVal:
    group: "MS Run"
    type: "paramMSRun"
    description: "Weights for intensity-dependence of non-detection."
    min: 0
    max: 1
    default: 0.1
  MSNoise:
    group: "MS Run"
    type: "paramMSRun"
    description: "Noise due to the MS instrument."
    min: 0
    max: 1
    default: 0.25
  WrongIDs:
    group: "MS Search"
    type: "paramMSRun"
    description: "Percentage of wrong identifications."
    min: 0
    max: 0.1
    default: 0.01
  WrongLocalizations:
    group: "MS Search"
    type: "paramMSRun"
    description: "Percentage of wrong localizations."
    min: 0
    max: 0.1
    default: 0
  MaxNAPerPep:
    group: "MS Search Results Filter"
    type: "paramMSRun"
    description: "Maximum number of NA values per peptide allowed."
    min: 0
    max: 100
    default: 100
  ProtSummarization:
    group: "Protein Summarization"
    type: "paramDataAnalysis"
    description: "Method for summarizing to proteins (e.g., sum.top3, medpolish)."
    min: NA
    max: NA
    default: "medpolish"
  MinUniquePep:
    group: "Protein Summarization"
    type: "paramDataAnalysis"
    description: "Minimum number of unique peptides available."
    min: 1
    max: 10
    default: 1
  StatPaired:
    group: "Statistical Testing"
    type: "paramDataAnalysis"
    description: "Whether the statistical testing is paired or unpaired."
    min: false
    max: true
    default: false
